export const OTHER_SECTION_HEADING = "Other";
export const FLOATING_FOCUS_BUTTON_HIDE_TIMEOUT = 3000
export const RELEASES_FETCH_LIMIT = 50
export const SEARCH_DEBOUNCE_TIMEOUT = 200
export const SLUG_LENGTH = 50
